CC=gcc
CFLAGS=-arch ppc -arch ppc64 -arch x86_64 -arch i386 -mmacosx-version-min=10.4 -O3

all: stripcodesig

stripcodesig: stripcodesig.c
	$(CC) $(CFLAGS) -I. -o $@ $<

clean:
	rm -f stripcodesig

install: stripcodesig
	cp -f stripcodesig /usr/local/bin/

